import pyautogui as py
import time as t
py.press("winleft")
t.sleep(2)
py.write("edge")
t.sleep(2)
py.press("enter")
t.sleep(2)
py.write("gmail")
t.sleep(2)
py.press("enter")
t.sleep(2)
py.click(323,550)
t.sleep(5)
py.write("dhuque4784@gmail.com")
t.sleep(5)
py.press("enter")
t.sleep(5)
py.write("Dhudui478410")
t.sleep(5)
py.press("enter")
t.sleep(5)
py.click(120,225)
t.sleep(3)
py.write("prof.humbertoltoledo@gmail.com")
t.sleep(3)
py.click(1765,505)
t.sleep(3)
py.write("desafio do betinha, Julia, Eduardo, Hiago e Arthur Bernardo")
t.sleep(3)
py.click(1285,1092)
t.sleep(3)
py.write(".py")
t.sleep(3)
py.press("enter")
t.sleep(3)
py.click(1152,1099)
t.sleep(3)
